import React from 'react';

const PrivacyPolicyPage = () => {
  return (
    <div className="min-h-screen bg-[#0F1014] pt-16">
      {/* Hero Section */}
      <div className="relative w-full h-[40vh] bg-gradient-to-b from-gray-900 to-[#0F1014]">
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="text-center">
            <h1 className="text-5xl font-bold text-white mb-4">Privacy Policy</h1>
            <div className="w-24 h-1 bg-white mx-auto"></div>
          </div>
        </div>
      </div>

      {/* Content Section */}
      <div className="max-w-4xl mx-auto px-8 py-12">
        <div className="space-y-8 text-gray-300">
          <p className="text-lg">Last updated: February 03, 2025</p>
          
          <div className="space-y-4">
            <p className="text-lg">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p className="text-lg">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300">Privacy Policy Generator</a>.</p>
          </div>

          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-white">Interpretation and Definitions</h2>
            <h3 className="text-xl font-semibold text-white">Interpretation</h3>
            <p className="text-lg">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          </div>

          <div className="space-y-6">
            <h3 className="text-xl font-semibold text-white">Definitions</h3>
            <p className="text-lg">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-4 text-lg">
              <li><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong className="text-white">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong className="text-white">Application</strong> refers to OurShelves, the software program provided by the Company.</li>
              <li><strong className="text-white">Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to OurShelves.</li>
              <li><strong className="text-white">Country</strong> refers to: Indiana, United States</li>
              <li><strong className="text-white">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong className="text-white">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong className="text-white">Service</strong> refers to the Application.</li>
              <li><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong className="text-white">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </div>

          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-white">Collecting and Using Your Personal Data</h2>
            <h3 className="text-xl font-semibold text-white">Types of Data Collected</h3>
            
            <div className="space-y-6">
              <h4 className="text-lg font-semibold text-white">Personal Data</h4>
              <p className="text-lg">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
              <ul className="list-disc pl-6 space-y-2 text-lg">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Usage Data</li>
              </ul>
            </div>

            <div className="space-y-4">
              <h4 className="text-lg font-semibold text-white">Usage Data</h4>
              <p className="text-lg">Usage Data is collected automatically when using the Service.</p>
              <p className="text-lg">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
              <p className="text-lg">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
              <p className="text-lg">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            </div>
          </div>

          {/* Rest of the sections with the same styling pattern */}
          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-white">Security of Your Personal Data</h2>
            <p className="text-lg">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          </div>

          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-white">Children's Privacy</h2>
            <p className="text-lg">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.</p>
          </div>

          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-white">Contact Us</h2>
            <p className="text-lg">If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul className="list-disc pl-6 text-lg">
              <li>By email: <a href="mailto:badhHarjyot99@gmail.com" className="text-blue-400 hover:text-blue-300">badhHarjyot99@gmail.com</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage;